import React,{useState}from"react";import{add,getDB,nextNumber,exportBackup,importBackup}from"../db";import{recordExpense,trialBalance}from"../services/accounting";
const T=({rows,cols})=><div style={{overflow:"auto"}}><table><thead><tr>{cols.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||i}>{cols.map(c=><td key={c}>{String(r[c]??"")}</td>)}</tr>)}</tbody></table></div>;
function Form({fields,onSave,label="حفظ"}){const[f,setF]=useState({});return <div><div className="form">{fields.map(([k,l,type])=><label key={k}>{l}<input type={type||"text"} value={f[k]||""} onChange={e=>setF({...f,[k]:e.target.value})}/></label>)}</div><button className="primary" onClick={()=>{try{onSave(f);setF({})}catch(e){alert(e.message)}}}>{label}</button></div>}
export default function SchoolOperations({type}){const db=getDB();const title={cash:"الصندوق والسندات",grades:"الكنترول والنتائج",attendance:"الحضور والغياب",employees:"الموظفون والرواتب",library:"المكتبة",inventory:"المخزون",accounting:"الحسابات والتقارير المالية"}[type]||"الوحدة";if(type==="cash")return <><h1>{title}</h1><section className="box"><h2>سند صرف</h2><Form fields={[[ "amount","المبلغ","number"],["description","البيان"]]} onSave={f=>recordExpense(f)}/></section><section className="box"><h2>حركة المصروفات</h2><T rows={db.expenses.slice().reverse()} cols={["number","date","amount","description"]}/></section></>;
if(type==="accounting")return <><h1>{title}</h1><section className="box"><h2>ميزان المراجعة</h2><T rows={trialBalance()} cols={["id","name","type","debit","credit"]}/></section><section className="box"><h2>دليل الحسابات</h2><T rows={db.accounts} cols={["id","name","type","balance"]}/></section></>;
if(type==="employees")return <><h1>{title}</h1><section className="box"><h2>إضافة موظف</h2><Form fields={[[ "name","الاسم"],["job","الوظيفة"],["salary","الراتب","number"],["phone","الهاتف"]]} onSave={f=>add("employees",{employeeNo:nextNumber("EMP"),...f,salary:Number(f.salary||0),status:"نشط"})}/><T rows={db.employees} cols={["employeeNo","name","job","salary","phone","status"]}/></section></>;
if(type==="grades")return <><h1>{title}</h1><section className="box"><h2>إدخال درجة</h2><Form fields={[[ "studentId","معرف الطالب"],["subject","المادة"],["period","الفترة"],["score","الدرجة /100","number"]]} onSave={f=>{const x=Number(f.score);if(x<0||x>100)throw Error("الدرجة من 0 إلى 100");add("grades",{...f,score:x})}}/><T rows={db.grades.slice().reverse()} cols={["studentId","subject","period","score"]}/></section></>;
if(type==="attendance")return <><h1>{title}</h1><section className="box"><Form fields={[[ "studentId","معرف الطالب"],["status","الحالة"]]} onSave={f=>add("attendance",{...f,date:new Date().toISOString().slice(0,10)})}/><T rows={db.attendance.slice().reverse()} cols={["date","studentId","status"]}/></section></>;
if(type==="library"||type==="inventory")return <><h1>{title}</h1><section className="box"><Form fields={[[ "name","اسم الصنف/الكتاب"],["details","التفاصيل"],["quantity","الكمية","number"]]} onSave={f=>add(type,{...f,quantity:Number(f.quantity||0)})}/><T rows={db[type]} cols={["name","details","quantity"]}/></section></>;
return null;}